### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by lmatteis** [cyclejs-community/redux-cycle-middleware#14]
I'm a bit of a newb with package.json and npm stuff, but it doesn't seem right that `xstream` and `run` are inside devDependencies. For instance, the jsonp driver has `xstream` as a peerDependency and `run` as a dependency: https://github.com/Widdershin/cycle-core/blob/bbad3d6ef832e6131f1c81a32de856b3d56ecda2/jsonp/package.json#L12

@nickbalestra @goshakkk not sure how peerDependencies work but maybe you guys can help?

**Comment by nickbalestra** [comment]
Yes those are actual dependencies, not devDepenencies

**Comment by lmatteis** [comment]
https://github.com/cyclejs-community/redux-cycle-middleware/pull/15
