### ISSUE TITLE
Example failing tests

### ISSUE THREAD

**Issue by lmatteis** [cyclejs-community/redux-cycle-middleware#16]
@nickbalestra can you try running `npm i` and `npm run test` on the example folder (with a clean install). I'm getting a weird `Error: Cannot find module '@cycle/time'` error and can't figure out why since @cycle/time is right there in package.json :(

**Comment by nickbalestra** [comment]
seemed all fine on my side
```
 Cycles
    fetchReposByUser
      ✓ should emit HTTP requests given ACTIONs
      ✓ should emit ACTION given HTTP response
  2 passing (338ms)
```
